# Generated by Django 5.2.6 on 2025-11-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='divided_price',
        ),
    ]
