# Generated by Django 5.2.6 on 2025-12-01 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_post_divided_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อเรื่อง')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('category', models.CharField(choices=[('BUG', 'แจ้งปัญหาการใช้งาน/บั๊ก'), ('USER', 'รายงานพฤติกรรมผู้ใช้'), ('SCAM', 'แจ้งเบาะแสการโกง'), ('OTHER', 'ข้อเสนอแนะ/อื่นๆ')], max_length=10, verbose_name='หมวดหมู่')),
                ('status', models.CharField(choices=[('PENDING', 'รอตรวจสอบ'), ('ACKNOWLEDGED', 'รับเรื่องแล้ว'), ('RESOLVED', 'ดำเนินการแก้ไขแล้ว'), ('REJECTED', 'ปฏิเสธ/ไม่พบปัญหา')], default='PENDING', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
