# Generated by Django 5.2.6 on 2025-12-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='report_evidence/', verbose_name='หลักฐานประกอบ (รูปภาพ)'),
        ),
    ]
