# Generated by Django 5.2.6 on 2025-12-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_report_evidence_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='resolution_note',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียดการแก้ไข'),
        ),
    ]
