import os
import dj_database_url




"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-a9b)wq_#+$-ow&_%dvl&$ax1d383k0)-(2y8m38+den1n@e$)m'
# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

#Deployment settings
# อ่านค่าจาก Environment ถ้าไม่มีให้เป็นค่า Default (สำหรับการทดสอบ)
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-your-dev-key')
# ถ้าบน Server จะเป็น False อัตโนมัติ
DEBUG = 'RENDER' not in os.environ 

ALLOWED_HOSTS = ['*'] # อนุญาตทุกโดเมน หรือใส่ชื่อเว็บคุณตอนได้มาแล้ว

# ALLOWED_HOSTS = ['busy-cricket-slowly.ngrok-free.app', 'localhost', '127.0.0.1',"busy-cricket-slowly.ngrok-free.app",'haandaibor.onrender.com',]
CSRF_TRUSTED_ORIGINS = ['https://*.onrender.com', 'https://*.ngrok-free.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',

    'django.contrib.sites',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'tailwind',
    'crispy_forms',
    'crispy_tailwind',
    'theme',
    
    'core',

    'cloudinary',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware', 
]

ROOT_URLCONF = 'config.urls'

import os
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'templates', 'allauth'),
            os.path.join(BASE_DIR, 'core', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.notifications',  # เพิ่ม context processor สำหรับการแจ้งเตือน
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if 'DATABASE_URL' in os.environ:
    # ✅ กรณีอยู่บน Vercel (Production)
    # มันจะอ่านค่าจาก Environment Variable ที่เราตั้งไว้ใน Vercel
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,
        )
    }
else:
    # ✅ กรณีอยู่บนเครื่องเรา (Localhost)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'haandaibor',
            'USER': 'postgres',      # ชื่อ User ของคุณ
            'PASSWORD': '1234',      # รหัสผ่านของคุณ
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }

# #deployment database settings
# DATABASES = {
#     'default': dj_database_url.config(
#         default='postgresql://postgres:1234@localhost:5432/haandaibor',
#         conn_max_age=600
#     )
# }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# โฟลเดอร์ที่จะรวบรวมไฟล์จริง
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 1
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

AUTH_USER_MODEL = 'core.User'


# import os
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '940563183804-53ckcqld1qjltadhg52l4a2gbeevqki1.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        }
    }
}

if DEBUG:
    # Add django_browser_reload only in DEBUG mode
    INSTALLED_APPS += ['django_browser_reload']

    MIDDLEWARE += ['django_browser_reload.middleware.BrowserReloadMiddleware']

TAILWIND_APP_NAME = "theme"
ACCOUNT_EMAIL_REQUIRED = True
EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = BASE_DIR / 'sent_emails'  # Emails will be saved here
# ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
# ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

# NPM_BIN_PATH = "C:/Program Files/nodejs/npm.cmd"

# === การตั้งค่าสำหรับ Ngrok และ HTTPS ===
# 1. บังคับให้ Allauth สร้างลิงก์เป็น https เสมอ
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

# 2. บอก Django ว่าถ้าเจอ Header นี้ (จาก ngrok) ให้ถือว่าเป็น HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 3. (เผื่อไว้) ป้องกัน CSRF Error เวลาใช้ https
CSRF_TRUSTED_ORIGINS = ['https://busy-cricket-slowly.ngrok-free.app']

SOCIALACCOUNT_LOGIN_ON_GET=True
SOCIALACCOUNT_AUTO_SIGNUP = True

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# settings.py (ล่างสุด)

# ตั้งค่าการ Authentication
# (แนะนำให้ใส่ใน Environment Variable ดีที่สุด แต่ถ้าจะ Test ในเครื่องชั่วคราว ใส่ String ตรงนี้ได้)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dyc5cviqh',
    'API_KEY': '552484323575527',
    'API_SECRET': 'oNTdzfFmg_GaI7WIP-gcuOXbPkY',
}
# หรือถ้าใช้ CLOUDINARY_URL แบบบรรทัดเดียว ระบบจะอ่านค่าจาก Environment เองอัตโนมัติ

# config/settings.py

# 1. เช็คว่านำเข้า os หรือยัง
import os

# 2. ต้องไม่มีบรรทัดนี้ลอยๆ อยู่ข้างนอก (ถ้ามีให้ลบออก หรือย้ายไปไว้ใน else)
# MEDIA_URL = '/media/'  <-- ❌ ตัวร้าย! ถ้าวางไว้ตรงนี้ มันจะทับการตั้งค่าของ Cloudinary

if 'CLOUDINARY_URL' in os.environ:
    # ✅ กรณีอยู่บน Render (มี Env Var)
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    print("--- Using Cloudinary Storage ---") # ใส่ไว้เช็คใน Log ได้
else:
    # ✅ กรณีอยู่บนเครื่อง (Local)
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'